metadata:
  annotations:
    ${deployment.annotations}
spec:
  replicas: ${deployment.replicas}
  template:
    spec:
      containers:
        - env:
            - name: SPRING_MESSAGES_BASENAME
              value: ${deployment.container.env.springMessagesBasename}
