apiVersion: networking.k8s.io/v1
kind: Ingress
spec:
  rules:
  - host: ${ingress.host}
    http:
      paths:
      - backend:
          service:
            name: ${project.artifactId}
            port:
              number: ${applicationPort}
        path: /
        pathType: ImplementationSpecific
